fix Directory_Tree_(Slave) Circular dependency
Fixed moving Directory_Tree(_Root).select to slave_statics.js
+using typescript "declare class" in new file tree/slave/declaration.ts (seen as a new class  different from Directory_Tree_Slave by modules implementing JS-Util, thus just a template copied/pasted in Directory_Tree)

Used to raise in Directory_Tree_Slave.js:2:43 :
> class Directory_Tree_Slave extends Directory_Tree
ReferenceError: Cannot access 'Directory_Tree' before initialization