fix fs.tree.Directory_Tree_Root.scan Unexpected super in Promise's arrow
Adding super_scan(...)
Because of a V8 bug, line 80 used to raise :
SyntaxError: 'super' keyword unexpected here
Cf. https://stackoverflow.com/questions/32932699/calling-super-method-inside-promise-super-keyword-unexpected-here